### ISSUE TITLE
Opinions about Safar Ali's project

### ISSUE THREAD

**Issue by Fsher07** [safar1212/Portfolio#4]
Maybe you can make background looks better. Other than that, I can only congratulate😊.
![1473970213_1678](https://user-images.githubusercontent.com/96717968/154426072-13cef06f-8e86-4733-a29a-e7a37bbf1fdc.gif)

**Comment by safar1212** [comment]
so guys, what are your comments regarding my mobile version code?

**Comment by LYANGEND** [comment]
I feel your HTML  layout is really good, I would only suggest you add margins to your sections to make them visible.Otherwise you have done a great job.

**Comment by safar1212** [comment]
https://media.giphy.com/media/RipfZWzjUDH25euMpM/giphy.gif

**Comment by safar1212** [comment]
https://media.giphy.com/media/RipfZWzjUDH25euMpM/giphy.gif

**Comment by safar1212** [comment]
<div style="width:100%;height:0;padding-bottom:100%;position:relative;"><iframe src="https://giphy.com/embed/RipfZWzjUDH25euMpM" width="100%" height="100%" style="position:absolute" frameBorder="0" class="giphy-embed" allowFullScreen></iframe></div><p><a href="https://giphy.com/gifs/kindafunny-thank-you-kinda-funny-greg-miller-RipfZWzjUDH25euMpM">via GIPHY</a></p>

**Comment by safar1212** [comment]
Thank you, everyone. I will try to solve those errors
